### PR TITLE
more doxygen

### LINKED ISSUE #114: What is the difference between ip_rot_equid_cylind_egrid and ip_rot_equid_cylind_grid?
What is the difference between ip_rot_equid_cylind_egrid and ip_rot_equid_cylind_grid?

They seem very similar. Documenation is wrong for ip_rot_equid_cylind_grid_mod (probably my mistake) but for ip_rot_equid_cylind_grid_mod it says:

```
!> @file
!! @brief Rotated equidistant cylindrical GRIB decoder and grid
!! coordinate transformations.
!! @author Mark Iredell, George Gayno, Kyle Gerheiser
!! @date July 2021

```

I need to know to fix documentation.

@GeorgeGayno-NOAA do you know? Thanks!

Part of #97.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #114 
Part of #97

More doxygen improvements.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I need help with the ??? in ip_rot_equid_cylind_grid_mod.

Will these variables have the same documentation in ip_rot_equid_cylind_egrid_mod?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I need help with the ??? in ip_rot_equid_cylind_grid_mod.
> 
> Will these variables have the same documentation in ip_rot_equid_cylind_egrid_mod?



> @GeorgeGayno-NOAA I need help with the ??? in ip_rot_equid_cylind_grid_mod.
> 
> Will these variables have the same documentation in ip_rot_equid_cylind_egrid_mod?

The same grid template number (3.1) is used. So the definitions are the same.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA if you can approve these changes I will merge them...

File: src/bicubic_interp_mod.F90 [hunk 1]
```diff
@@ -1,10 +1,10 @@
 !> @file
-!! @brief Bicubic interpolation routines for scalars and vectors
-!! @author Mark Iredell, Kyle Gerheiser
+!> @brief Bicubic interpolation routines for scalars and vectors
+!> @author Mark Iredell, Kyle Gerheiser
 
-!> Bicubic interpolation routines for scalars and vectors
-!!
-!! @author George Gayno, Mark Iredell, Kyle Gerheiser
+!> @brief Bicubic interpolation routines for scalars and vectors.
```
Comment (GeorgeGayno-NOAA) [inline src/bicubic_interp_mod.F90:5]: Why repeat this at line 2?

File: src/ipolatev.F90 [hunk 2]
```diff
@@ -1,12 +1,13 @@
...
-!> Top-level driver for vector interpolation interpolation routine ipolates.
-!! Ipolatev is overloaded with interfaces for grib1 and grib2 descriptors
-!!
-!! @author George Gayno, Mark Iredell, Kyle Gerheiser
+!> @brief Top-level driver for vector interpolation routine ipolates.
+!> @author Mark Iredell, Kyle Gerheiser
+!> @date July 2021
+
+!> @brief Top-level driver for vector interpolation interpolation
+!> routine ipolates.  Ipolatev is overloaded with interfaces for grib1
```
Comment (GeorgeGayno-NOAA) [inline src/ipolatev.F90]: "ipolatev"?

File: src/bicubic_interp_mod.F90 (hunk 1 above)
Comment (edwardhartnett) [reply src/bicubic_interp_mod.F90:5]: One is for the file, the other for the module.

File: src/ipolatev.F90 [hunk 3]
```diff
@@ -595,53 +598,53 @@ subroutine ipolatev_grib1(ip,ipopt,kgdsi,kgdso,mi,mo,km,ibi,li,ui,vi, &
...
-  !! - 1 Unrecognized interpolation method.
-  !! - 2 Unrecognized input grid or no grid overlap.
-  !! - 3 Unrecognized output grid.
-  !! - 1x Invalid bicubic method parameters.
-  !! - 3x Invalid budget method parameters.
-  !! - 4x Invalid spectral method parameters.
-  !!
-  !! @date Jan 2022
-  !! @author Kyle Gerheiser
+  !> Removes the km dimension of input arrays so scalars can be passed to ibi/ibo.
```
Comment (GeorgeGayno-NOAA) [inline src/ipolatev.F90]: vectors?

File: src/bicubic_interp_mod.F90 (hunk 1 above)
Comment (GeorgeGayno-NOAA) [reply src/bicubic_interp_mod.F90:5]: Is the second @brief for the 'module' statement only?

File: src/ipolatev.F90 (hunk 2 above)
Comment (edwardhartnett) [reply src/ipolatev.F90]: Fixed

File: src/ipolatev.F90 (hunk 3 above)
Comment (edwardhartnett) [reply src/ipolatev.F90]: fixed...

File: src/bicubic_interp_mod.F90 (hunk 1 above)
Comment (edwardhartnett) [reply src/bicubic_interp_mod.F90:5]: Yes. One brief for the file, one for the module. Then, when doxygen lists the file we see it:

image

And when we look at the list of modules we also see it:

image

This seems redundant but if we were to write a file with two modules, it would work out. Also, if we don't use both briefs, either the file list or the module list would have no documentation.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA if you can approve I will merge and continue in a new PR.

File: src/bicubic_interp_mod.F90 (hunk 1 above)
Comment (GeorgeGayno-NOAA) [reply src/bicubic_interp_mod.F90:5]: Great.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
