### PR TITLE
doxygen fixes

### LINKED ISSUE #89: in Doxyfile, turn on REFERENCED_BY_RELATION and REFERENCES_RELATION
These should be turned on to give the calling and called functions in the documentation.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #86 
Part of #60 
Fixes #89

Some doxygen fixes. @kgerheiser and @GeorgeGayno-NOAA there are some "???" in here where I didn't know what to put. Can you tell me?

### CODE REVIEW

File: src/ip_equid_cylind_grid_mod.f90 [hunk 1]
```diff
@@ -25,9 +27,9 @@ module ip_equid_cylind_grid_mod
      procedure :: gdswzd => gdswzd_equid_cylind
   end type ip_equid_cylind_grid
 
-  REAL                    :: DLAT ! GRID RESOLUTION IN DEGREES N/S DIRECTION
-  REAL                    :: DLON ! GRID RESOLUTION IN DEGREES E/W DIRECTION
-  REAL                    :: RERTH
+  REAL :: DLAT !< Grid resolution in degrees n/s direction.
+  REAL :: DLON !< Grid resolution in degrees e/w direction.
+  REAL :: RERTH !< ???
```
Comment (kgerheiser) [inline src/ip_equid_cylind_grid_mod.f90]: Radius of the Earth

**Comment by edwardhartnett** [comment]
@kgerheiser can you approve please so I can merge these changes?

**Review by kgerheiser — APPROVED** [review]
