### PR TITLE
Add Doxygen documentation to ipolatev and fix some ipolates mistakes

### LINKED ISSUE #58: Fix Doxygen in ipolates.f90
Several typos and gaps between lines.

### LINKED ISSUE #59: Add Doxygen to ipolatev.f90

### PR DESCRIPTION
**Pull request by kgerheiser**
Fix #59
Fix #58

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Can you provide a description of each PR, with a link to the issues being addressed?

File: src/ipolatev.f90 [hunk 1]
```diff
@@ -16,6 +25,37 @@ module ipolatev_mod
 
 contains
 
+  !> @brief Interpolates scalar fields between grids given ip_grid objects.
```
Comment (edwardhartnett) [inline src/ipolatev.f90]: No need to brief tag for subroutines/functions.

File: src/ipolatev.f90 [hunk 2]
```diff
@@ -16,6 +25,37 @@ module ipolatev_mod
...
+  !! @details Calls the specific interpolation routines on the generic ip_grids created from a grib1/grib2 descriptor.
+  !! @param[in]  ip Interpolation method.
```
Comment (edwardhartnett) [inline src/ipolatev.f90]: Clean up spacing for this and following lines. One space is all we ever need.

File: src/ipolatev.f90 [hunk 3]
```diff
@@ -16,6 +25,37 @@ module ipolatev_mod
...
+  !! @param[out] vo  Output v-component fields interpolated.
+  !! @param[out] iret Return code.
+  !! - 0 Successful interpolation.
+  !! - 1 Unrecognized interpolation method.
+  !! - 2 Unrecognized input grid or no grid overlap.
+  !! - 3 Unrecognized output grid.
+  !! - 1x Invalid bicubic method parameters.
+  !! - 3x Invalid budget method parameters.
+  !! - 4x Invalid spectral method parameters.
+  !! @date July 2021
```
Comment (edwardhartnett) [inline src/ipolatev.f90:61]: Author tag for all subroutines/functuons.

File: src/ipolatev.f90 [hunk 4]
```diff
@@ -1,3 +1,12 @@
+!> @file
+!! @brief Top-level driver for vector interpolation routine ipolates.
+!! @author Mark Iredell, Kyle Gerheiser
```
Comment (edwardhartnett) [inline src/ipolatev.f90:3]: Don't add your name unless you have authored some of the code in the file. Doxygen reformatting is not code.

File: src/ipolatev.f90 [hunk 5]
```diff
@@ -70,307 +110,260 @@ SUBROUTINE ipolatev_grid(IP,IPOPT,grid_in,grid_out, &
...
-  !   SPECTRAL    4   0,-1           12.60
-  !   N-BUDGET    6   0,-1            0.33
-  !
-  ! ATTRIBUTES:
-  !   LANGUAGE: FORTRAN 90
-  !
-  !$$$
+  
+  !> @brief This subprogram interpolates vector fields from any grid to any grid given a grib2 descriptor.
+  !! @details Wrapper for ipolates_grid which converts a grib1 descriptor into an ip_grid_descriptor,
```
Comment (edwardhartnett) [inline src/ipolatev.f90]: Don't need the details tag.

File: src/ipolatev.f90 [hunk 6]
```diff
@@ -70,307 +110,260 @@ SUBROUTINE ipolatev_grid(IP,IPOPT,grid_in,grid_out, &
...
+  !! - 30 - LAMBERT CONFORMAL CONICAL
+  !! - 40 - GAUSSIAN EQUIDISTANT CYCLINDRICAL
+  !!
+  !! @param[in] igdtmpli Grid definition template array input grid.
+  !! Corresponds to the gfld%igdtmpl component of the NCEPLIBS-g2 gridmod data structure
+  !!
+  !! Section 3 Info:
+  !!
+  !! All map projections:
+  !! - (1): SHAPE OF EARTH, OCTET 15
```
Comment (edwardhartnett) [inline src/ipolatev.f90]: lower-case all these...

File: src/ipolatev.f90 [hunk 7]
```diff
@@ -70,307 +110,260 @@ SUBROUTINE ipolatev_grid(IP,IPOPT,grid_in,grid_out, &
...
+  !!   --------| --|-------------| ----------
+  !!   BILINEAR| 0 |             |   0.05
+  !!   BICUBIC | 1 | 0           |   0.16
+  !!   BICUBIC | 1 | 1           |   0.17
+  !!   NEIGHBOR| 2 |             |   0.02
+  !!   BUDGET  | 3 | -1,-1       |   0.94
+  !!   SPECTRAL| 4 | 0,40        |   0.31
+  !!   SPECTRAL| 4 | 1,40        |   0.33
+  !!   SPECTRAL| 4 | 0,-1        |   0.59
+  !!   N-BUDGET| 6 | -1,-1       |   0.31
```
Comment (edwardhartnett) [inline src/ipolatev.f90:356]: Nice use of table!

File: src/ipolatev.f90 [hunk 8]
```diff
@@ -70,307 +110,260 @@ SUBROUTINE ipolatev_grid(IP,IPOPT,grid_in,grid_out, &
...
+  !! Note: igdtnumo<0 means interpolate to random station points.
+  !!
+  !! @param[in] igdtmplo Grid definition template array for the output grid.
+  !! Corresponds to the gfld%igdtmpl component of the ncep g2 library gridmod data structure.
+  !! See "igdtmpli" for definition of array elements.
+  !!
+  !! @param[in] igdtleno Number of elements of the grid definition template array for the output grid.  c
+  !! Corresponds to the gfld%igdtlen component of the ncep g2 library gridmod data structure.
+  !!
+  !! @param[in] mi    Skip number between input grid fields if km>1 or dimension of input grid fields if km=1.
```
Comment (edwardhartnett) [inline src/ipolatev.f90]: Are the parameters all in the same order as the function declaration? Lots of the legacy documentation messed up the ordering to support INPUT vs. OUTPUT, but in the doxygen we want the same exact ordering as in the function declaration...

File: src/ipolatev.f90 [hunk 9]
```diff
@@ -409,163 +402,130 @@ SUBROUTINE IPOLATEV_grib2(IP,IPOPT,IGDTNUMI,IGDTMPLI,IGDTLENI, &
...
+  !!   --------| --| -------------|----------
+  !!   BILINEAR| 0 |              | 0.05
+  !!   BICUBIC | 1 | 0            | 0.15
+  !!   BICUBIC | 1 | 1            | 0.16
+  !!   NEIGHBOR| 2 |              | 0.02
+  !!   BUDGET  | 3 | -1,-1        | 0.92
+  !!   SPECTRAL| 4 | 0,40         | 4.51
+  !!   SPECTRAL| 4 | 1,40         | 5.77
+  !!   SPECTRAL| 4 | 0,-1         | 12.60
+  !!   N-BUDGET| 6 | -1,-1        | 0.33
```
Comment (edwardhartnett) [inline src/ipolatev.f90:542]: Not a comment on your doxygenation, but what scares me is testing this kind of function. I rather suspect that many of these options are never used anywhere, but all will have to be tested.

**Review by edwardhartnett — CHANGES_REQUESTED** [review]

File: src/ipolatev.f90 (hunk 1 above)
Comment (kgerheiser) [reply src/ipolatev.f90]: Can I keep the `@details`?

File: src/ipolatev.f90 (hunk 4 above)
Comment (kgerheiser) [reply src/ipolatev.f90:3]: I authored a lot of the code here when combining them

File: src/ipolatev.f90 (hunk 8 above)
Comment (kgerheiser) [reply src/ipolatev.f90]: Yes, I made sure they were in the same order.

File: src/ipolatev.f90 (hunk 1 above)
Comment (edwardhartnett) [reply src/ipolatev.f90]: Why keep it? Is it adding something to the output? If not, then don't keep it. We would like all our doxygen to look similar, so that programmers can easily contribute doxygen to any of the NCEPLIBS codes.

File: src/ipolatev.f90 [hunk 10]
```diff
@@ -527,8 +541,10 @@ END SUBROUTINE IPOLATEV_GRIB2
   !!   SPECTRAL| 4 | 0,-1         | 12.60
   !!   N-BUDGET| 6 | -1,-1        | 0.33
   !!
-  SUBROUTINE IPOLATEV_grib1(IP,IPOPT,KGDSI,KGDSO,MI,MO,KM,IBI,LI,UI,VI, &
-       NO,RLAT,RLON,CROT,SROT,IBO,LO,UO,VO,IRET) bind(c)
+  !! @date July 2021
+  !! @author Kyle Gerheiser
+  subroutine ipolatev_grib1(ip,ipopt,kgdsi,kgdso,mi,mo,km,ibi,li,ui,vi, &
```
Comment (edwardhartnett) [inline src/ipolatev.f90:546]: I would not lower-case the code. Was this intentional?

Try and keep code changes to a minimum, or have no code changes at all, for the documentation tasks. That makes them easy to review. The first thing I look at in mine or @Hang-Lei-NOAA 's is that no lines of code changed. That way we know we are not breaking anything.

**Review by edwardhartnett — APPROVED** [review]

File: src/ipolatev.f90 (hunk 10 above)
Comment (kgerheiser) [reply src/ipolatev.f90:546]: Ok, I'll avoid doing that. It was intentional because the Doxygen params take the case of the variables in the function declaration.
